DEFAULT_STARDOG_CLOUD_ENDPOINT = "https://cloud.stardog.com/api"

DEFAULT_CLIENT_ID = "VBX-LANGCHAIN"

# Environment variable names
ENV_VOICEBOX_API_TOKEN = "SD_VOICEBOX_API_TOKEN"
ENV_VOICEBOX_CLIENT_ID = "SD_VOICEBOX_CLIENT_ID"
ENV_CLOUD_ENDPOINT = "SD_CLOUD_ENDPOINT"
